
from abc import ABC

class Skeleton(ABC):
    __owner: str
    __name: str

    def __set_name__(self, owner, name: str) -> None: ...

    @property
    def owner(self) -> any: ...
    @property
    def name(self) -> str: ...

    def __set__(self, instance, value: any) -> None: ...
    def __get__(self, instance, owner) -> any: ...

    ...

class DataType(Skeleton):
    __permission: set[type or any or None]
    __PERMISSION_MESSAGE: str

    def __init__(self, *permission_dtypes: type | None): ...

    @property
    def permission(self) -> tuple: ...

    def __set__(self, instance, value: any) -> None: ...

    ...

class Constant(Skeleton):
    __value: any
    __NOT_ASSIGNABLE_MESSAGE: str

    def __init__(self, constant_value: any): ...

    def __set__(self, instance, value: any) -> None: ...
    def __get__(self, instance, owner) -> any: ...

    ...
